### ISSUE TITLE
Implement timeouts for http connections

### ISSUE THREAD

**Issue by acmiyaguchi** [acmiyaguchi/game.moonlight#5]
Connections are currently all blocking processes without timeouts, which while fine for a command line instance, causes the rest of Kodi to freeze.

**Comment by acmiyaguchi** [comment]
Worst case scenario, kodi will freeze up to 5 seconds. I'm not sure how to prevent functions from blocking the main ui updates, but this isn't too big of an issue.

**Comment by garbear** [comment]
i get the same freezes when launching netplay with an invalid server. I'll look into offloading the game client initialization to another thread in retroplayer
