### ISSUE TITLE
Add support for input

### ISSUE THREAD

**Issue by acmiyaguchi** [acmiyaguchi/game.moonlight#7]
Now that video streaming is working, getting input to work should be the new priority. I need to take a look into figuring out if mouse and keyboard events are supported by peripheral.joystick, and also take a look at the input callbacks.

**Comment by garbear** [comment]
do you have a pretty good idea of how the game api's input system works? Use the OpenPort(##) callback as many times as you have ports (probably 4? how many players does gamestream support?)

Kodi then looks at the &lt;import> tags in addon.xml: https://github.com/kodi-game/game.libretro.nestopia/blob/master/game.libretro.nestopia/addon.xml#L8

If no &lt;import> tag is specified, then Kodi uses the default controller (you probably want this, so don't import any controllers)

Kodi then calls UpdatePort() whenever a controller is connected or disconnected to a port. you can probably ignore this, and assume that a controller is always connected (it just won't report any input)

I designed the input system from scratch, so it might be suboptimal for your purposes. lemme know if you need anything in the API tweaked - it's definitely not set in stone
